/*\
title: $:/plugins/tobibeer/setvars/widgets.js
type: application/javascript
module-type: widget

Allows to set multiple variables in one go joining widget attributes:

@preserve
\*/
(function(){"use strict";var e=require("$:/core/modules/widgets/widget.js").widget;var t=function(t,i){e.call(this);this.initialise(t,i)};t.prototype=Object.create(e.prototype);t.prototype.render=function(e,t){this.parentDomNode=e;this.computeAttributes();this.execute();this.renderChildren(e,t)};t.prototype.execute=function(){var e=this,t=function(t,i,s){var r,n,f=s[3],a=s[4],l=s[5],u=s[6],h=parseInt(f),c=parseInt(a),o=i||f||a;if(i){n=e.wiki.filterTiddlers(t,e)}else{n=f||a?$tw.utils.parseStringArray(t):[t]}r=n.length;if(r&&(f||a)){if(f==="n"){h=r}else if(f==="-n"){h=1}else if(!f){h=1}if(a==="n"){c=r}else if(a==="-n"){c=-(h<0?r+h+1:h)}else if(!a){c=1}h=Math.max(1,h<0?r+h+(c<0?c+2:1):c<0?h+c+1:h);c=Math.max(1,Math.abs(c));n=n.splice(h-1,c)}if(!n.length&&l){n.push(l)}return o?u===undefined?$tw.utils.stringifyList(n):n.join(u):n[0]};this.set={};this.use={};$tw.utils.each(this.attributes,function(t,i){if(i.charAt(0)==="_"){e.use[i.substr(1)]=t}else{e.set[i]=t}});$tw.utils.each(e.set,function(i,s){var r,n,f,a,l,u,h,c,o="",p=0,d="",b=i,g=[[/^\s+/,1,function(){return false}],[/^\\([^\\]*)\\/,2,function(e){return e[1]}],[/^(if\s*\(|\?|\:|\|\||\))/i,0,function(e){if(e[1].substr(0,2).toLowerCase()==="if"){a=1;l=u=h=c=p=0;r=""}else{switch(e[1]){case"||":if(o&&o.length){p=1}break;case"?":if(a){l=r.length;u=1;p=0;r=o=""}break;case":":if(a){h=c=1;if(l){d+=r}u=p=0;r=o=""}break;case")":if(a){if(!l||!c){d+=r}a=l=u=h=p=0;r="";o=""}break}}return false}],[/^(\[)?(\w+)(?:\[(-?\d*|-?n)(?:,(-?\d*|-?n))?\])?(?:\[([^\]]*)\])?(?:\[([^\]]*)\])?(\])?/,2,function(i){var s=e.use[i[2]];if(s){if(i[1]&&i[7]){s=t(s,true,i)}else if(!i[1]&&!i[7]){s=t(s,false,i)}else{s=null}}return s}]];while(b.length){f=b;var v="";$tw.utils.each(g,function(e){var t=e[0].exec(b);if(t){if(!p||!e[1]){v=e[2].call(this,t);if(v===null){v="error: missing bracket in setvars"}else if(v){if(a&&(u&&l||h&&!l)){p=1}}if(v!==false){o=v}}n=e[1]===2;b=b.substr(t[0].length);return false}});if(v){if(a){r+=v}else if(!p){d+=v}}if(!a&&n){p=0}if(f===b){d="error: invalid setvars syntax";b=""}}e.setVariable(s,d)});this.makeChildWidgets()};t.prototype.refresh=function(e){var t=this.computeAttributes();if(Object.keys(t).length){this.refreshSelf();return true}return this.refreshChildren(e)};exports.setvars=t})();