/*\
title: $:/plugins/tobibeer/setvars/widgets.js
type: application/javascript
module-type: widget

Allows to set multiple variables in one go joining widget attributes:

@preserve
\*/
(function(){"use strict";var e=require("$:/core/modules/widgets/widget.js").widget;var t=function(t,s){e.call(this);this.initialise(t,s)};t.prototype=Object.create(e.prototype);t.prototype.render=function(e,t){this.parentDomNode=e;this.computeAttributes();this.execute();this.renderChildren(e,t)};t.prototype.execute=function(){var e=this,t=function(t,s,i){var r,n,u,f=i[3],h=i[4],l=i[5],a=parseInt(f),c=parseInt(h);if(s){n=e.wiki.filterTiddlers(t,e)}else{n=f||h?$tw.utils.parseStringArray(t):[t]}r=n.length;if(r&&(f||h)){if(f==="n"){a=r}else if(f==="-n"){a=1}else if(!f){a=1}if(h==="n"){c=r}else if(h==="-n"){c=-(a<0?r+a+1:a)}else if(!h){c=1}u=a;a=Math.max(1,a<0?r+a+(c<0?c+2:1):c<0?a+c+1:a);c=Math.max(1,Math.abs(c));n=n.splice(a-1,c)}if(l&&!n.length){n.push(l)}return $tw.utils.stringifyList(n)};this.set={};this.use={};$tw.utils.each(this.attributes,function(t,s){if(s.charAt(0)==="_"){e.use[s.substr(1)]=t}else{e.set[s]=t}});$tw.utils.each(e.set,function(s,i){var r,n,u,f="",h,l=/^(\[)?(\w+)(?:\[(-?\d*|-?n)(?:,(-?\d*|-?n))?\])?(?:\[([^\]]*)\])?(\])?(?:\s|$)/,a=s;while(a){h=a;n=/^\s/.exec(a);if(n){a=a.substr(n[0].length)}n=/^\\([^\\]*)\\/.exec(a);if(n){f+=n[1];a=a.substr(n[0].length)}n=l.exec(a);if(n){u=e.use[n[2]];if(u){if(n[1]&&n[6]){f+=t(u,true,n)}else if(!n[1]&&!n[6]){f+=t(u,false,n)}else{f+="setvars: missing bracket"}}a=a.substr(n[0].length)}if(a===h){r=a.indexOf(" ");a=r<0?"":a.substr(r+1)}}e.setVariable(i,f)});this.makeChildWidgets()};t.prototype.refresh=function(e){var t=this.computeAttributes();if(Object.keys(t).length){this.refreshSelf();return true}return this.refreshChildren(e)};exports.setvars=t})();