/*\
title: $:/plugins/tobibeer/setvars/widgets.js
type: application/javascript
module-type: widget

Allows to set multiple variables in one go joining widget attributes:

@preserve
\*/
(function(){"use strict";var e=require("$:/core/modules/widgets/widget.js").widget;var t=function(t,i){e.call(this);this.initialise(t,i)};t.prototype=Object.create(e.prototype);t.prototype.render=function(e,t){this.parentDomNode=e;this.computeAttributes();this.execute();this.renderChildren(e,t)};t.prototype.execute=function(){var e=this,t=function(t,i,s){var r,n,f=s[3],h=s[4],a=s[5],l=s[6],u=parseInt(f),c=parseInt(h),o=i||f||h;if(i){n=e.wiki.filterTiddlers(t,e)}else{n=f||h?$tw.utils.parseStringArray(t):[t]}r=n.length;if(r&&(f||h)){if(f==="n"){u=r}else if(f==="-n"){u=1}else if(!f){u=1}if(h==="n"){c=r}else if(h==="-n"){c=-(u<0?r+u+1:u)}else if(!h){c=1}u=Math.max(1,u<0?r+u+(c<0?c+2:1):c<0?u+c+1:u);c=Math.max(1,Math.abs(c));n=n.splice(u-1,c)}if(!n.length&&a){n.push(a)}return o?l===undefined?$tw.utils.stringifyList(n):n.join(l):n[0]};if(!this.refreshing){this.refreshing=0;this.$={vars:{},attr:{},set:{}};$tw.utils.each(this.attributes,function(t,i){if(i==="$refresh"){e.refreshAll=1}else if(i.charAt(0)==="_"){e.$.attr[i.substr(1)]=t}else{e.$.vars[i]=t}})}if(this.refreshing<2){$tw.utils.each(e.$.vars,function(i,s){var r,n,f,h,a,l="",u=0,c=0,o="",g=i,d=[[/^\s+/,1,function(){return false}],[/^\\([^\\]*)\\/,2,function(e){return e[1]}],[/^(if\s*\(|\?|\:|\|\||\))/i,0,function(e){if(e[1].substr(0,2).toLowerCase()==="if"){r=1;if(u){c=1}else{n=u=0;f=""}}else{switch(e[1]){case"||":if(l.length){u=1}break;case"?":if(r&&!c){n=f.length;u=!n;f=""}break;case")":if(r){if(n){o+=f}r=n=u=0;f=""}c=0;break}}return false}],[/^(\[)?(\w+)(?:\[(-?\d*|-?n)(?:,(-?\d*|-?n))?\])?(?:\[([^\]]*)\])?(?:\[([^\]]*)\])?(\])?/,2,function(i){var s=e.$.attr[i[2]];if(s===undefined){s=e.$.set[i[2]]}if(s){if(i[1]&&i[7]){s=t(s,true,i)}else if(!i[1]&&!i[7]){s=t(s,false,i)}else{s=null}}return s}]];while(g.length){a=g;var p="";$tw.utils.each(d,function(e){var t=e[0].exec(g);if(t){if(!u||!e[1]){p=e[2].call(this,t);if(p===null){p="error: missing bracket in setvars"}else if(p){l=p}}h=e[1]===2;g=g.substr(t[0].length);return false}});if(p){if(r){f+=p}else if(!u){o+=p}}if(!r&&h){u=0}if(a===g){o="error: invalid setvars syntax";g=""}}e.$.set[s]=o;e.setVariable(s,o)})}if(!this.refreshing||this.refreshing===2){this.makeChildWidgets()}};t.prototype.refresh=function(e){var t=0,i,s=this,r=this.computeAttributes();if(Object.keys(r).length){this.refreshSelf();return true}else if(this.refreshAll){i=JSON.parse(JSON.stringify(this.$.set));this.refreshing=1;this.execute();$tw.utils.each(i,function(e,i){if(e!==s.$.set[i]){t=1;return false}});if(t){this.refreshing=2;this.refreshSelf();return true}this.refreshing=0}return this.refreshChildren(e)};exports.setvars=t})();